### ISSUE TITLE
Convert Product Launch milestone's issues into document

### ISSUE THREAD

**Issue by xiaoland** [InKCre/InKCre-docu#4]
Requirements are just as the same in https://github.com/InKCre/.github/issues/12

### Content
- [ ] https://github.com/InKCre/InKCre/issues/1
- [ ] https://github.com/InKCre/InKCre/issues/2
- [ ] https://github.com/InKCre/InKCre/issues/3
